function about() {
  return <div>about page</div>;
}

export const metadata = {
  title: "Frontend Mentor | myteam website challenge - About",
  description: "Generated by create next app",
};

export default about;
