function contact() {
  return (
    <>
      <div className="container text-center h-80 bg-primary-midnight-green py-28">
        <h1>Contact</h1>
      </div>
    </>
  );
}

export const metadata = {
  title: "Frontend Mentor | myteam website challenge - Contact",
  description: "Generated by create next app",
};

export default contact;
