function contact() {
  return <div>contact page</div>;
}

export const metadata = {
  title: "Frontend Mentor | myteam website challenge - Contact",
  description: "Generated by create next app",
};

export default contact;
